// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctxwcgikyftfzlrtnvnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0eHdjZ2lreWZ0ZnpscnRudm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDQyMzQsImV4cCI6MjA3MTEyMDIzNH0.QWRA7CfOdJuTjuuc6D3jWFhdMFlqhOPKBi-QYuSHfLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});